CREATE DEFINER=`root`@`localhost` FUNCTION `udf_getPileID`(
	`p_pileName` VARCHAR(21)
)
RETURNS tinyint(4)
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT ''
BEGIN
	DECLARE pileID TINYINT;
	
	SELECT ID INTO pileID
	FROM cardPile
	WHERE pileName = p_pileName;
	
	RETURN pileID;
END